sudo: required
language: cpp
compiler: gcc
script:
  - sudo bash ./tools/ci_build.sh
  - sudo cp target/deepdark target/deepdark.linux.x64
matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
deploy:
  provider: releases
  api_key: "$GITHUB_API_KEY"
  file: "target/deepdark.linux.x64"
  skip_cleanup: true
  on:
    tags: true
